name: Request Review

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Check Payload
      run: |
        sudo apt-get update
        MARKDOWN=$(jq --raw-output .client_payload .markdown "${GITHUB_EVENT_PATH}");        
        echo $MARKDOWN
        USERNAME=$(jq --raw-output .client_payload .username "${GITHUB_EVENT_PATH}");        
        echo $USERNAME
        echo ${MARKDOWN} > README.md
    - name: Checkout New Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GitHub Actor: ${GITHUB_ACTOR}"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git branch
        git checkout -b update/term-$(date '+%Y-%m-%d')
        git branch

        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        #git add _data/memberCounts.csv
        #git commit -m "Automated deployment to update Member Counts $(date '+%Y-%m-%d')" --allow-empty
        #git push origin update/member-count-$(date '+%Y-%m-%d')
    - name: Open pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_AGAINST: "master"
      run: |
          export BRANCH_FROM="update/term-$(date '+%Y-%m-%d')"
          /bin/bash .github/workflows/pull-request.sh
