name: update-template

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Update Template via Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT_NAME: update-template
        BRANCH_AGAINST: "master"
      run: |
        event_name=$(jq --raw-output .client_payload.event_name "${GITHUB_EVENT_PATH}");
        if [ "${event_name}" != "${EVENT_NAME}" ]; then
            echo "Dispatch Event is not intended to update template"
            exit 0;
        fi
        TEMPLATE_REPO=$(jq --raw-output .client_payload.template_repo "${GITHUB_EVENT_PATH}")
        # If the repository name is the upstream template, don't run
        if [ "${GITHUB_REPOSITORY}" == "${TEMPLATE_REPO}" ]; then
            echo "This is the template, will not edit."
            exit 0;
        fi
        # Checkout template to tmp, move files
        git clone "${TEMPLATE_REPO}" /tmp/template
        cp -R /tmp/template/.github/* .github/
        # Open pull request to update template;
        echo "GitHub Actor: ${GITHUB_ACTOR}";
        export BRANCH_FROM="update/template-$(date '+%Y-%m-%d')";
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git";
        git branch;
        git checkout -b "${BRANCH_FROM}";
        git branch;
        git config --global user.name "github-actions";
        git config --global user.email "github-actions@users.noreply.github.com";
        git add .github/workflows/*;
        git commit -m "Update from template ${TEMPLATE_REPO} $(date '+%Y-%m-%d')" --allow-empty;
        git push origin "${BRANCH_FROM}";
        /bin/bash .github/workflows/update-template.sh;
